name: update-list

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *" # UTC

jobs:
  update-list:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup wget
      env:
          GREYNOISE_URL1: "https://api.greynoise.io/v3/tags/4454bcc7-d416-4bc9-8e85-e860c82369c2/ips?format=txt"
          GREYNOISE_URL2: "https://api.greynoise.io/v3/tags/877ae200-de27-46d6-ad65-e99c6df0ac1a/ips?format=txt"
          GREYNOISE_URL3: "https://api.greynoise.io/v3/tags/f620e81c-eaf4-477f-8bc4-ec94ca672615/ips?format=txt"
          
      run: |
          rm ip-list.txt
          rm -rf blocklist
          mkdir blocklist
          wget -i urltable -P blocklist/
          wget "$GREYNOISE_URL1"&token=${{ secrets.SECKEY_1 }}" -P blocklist/
          wget "$GREYNOISE_URL2"&token=${{ secrets.SECKEY_2 }}" -P blocklist/
          wget "$GREYNOISE_URL3"&token=${{ secrets.SECKEY_3 }}" -P blocklist/

    - name: Merge
      run: |
          cd blocklist
          cat * >> output
          sed -i 's/#.*//' output
          sed -i 's/;.*//' output
          cat -n output | sort -uk2 | sort -nk1 | cut -f2- > ip-list.txt
          cd ..
          cp blocklist/ip-list.txt .
          rm -rf blocklist
          
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply update-list changes
