name: update-list

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup wget
      run: |
          mkdir blocklist
          wget -i urltable -P blocklist/

    - name: Merge
      run: |
          cd blocklist
          cat * >> output
          sed -i '/^#/d' output
          sort -u output > ~/ip-list.txt
          
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply update-list changes
